### ISSUE TITLE
Add batch_size parameter

### ISSUE THREAD

**Issue by abertranb** [pagevamp/laravel-cloudwatch-logs#26]
Hi I suggest to add this and add on readme too
```
'batch_size' => env('CLOUDWATCH_LOG_BATCH_SIZE', 10000),
```
because the first time you test it you don't see events and on develop generate 10K events is hard

Thanks for this helpful package!

**Comment by developernaren** [comment]
I do not think it works that way. Batch size is for a single request I think. You can log and see even a single log to cloudwatch. If it does not work, it is more than likely, your credentials are wrong. In my typical tests, I send single log and immediately see in cloudwatch.

One thing that this might solve is the log from tinker, I think the logs are not being sent on tinker or queues, because those are long running process that does not terminate and because it does not reach 10k the log are lost. will look into this.

**Comment by developernaren** [comment]
https://github.com/pagevamp/laravel-cloudwatch-logs/releases/tag/v1.0.1 supports this, closing
